config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount ShopifyApp::Engine, at: '/'
  
  root :to => 'home#index'

  resources :products do

  	resources :stocks do
  	
  	end

  end

  resources :setup_requests do
  end

  resources :faq do

  end

  resources :product_profiles do
    
  end


end

app/views/common/_footer.html.erb
  <!-- Footer -->
  <footer class="footer text-right">
      <div class="container">
          <div class="row">
              <div class="col-xs-6">
                  <%= Time.now.year %> © Alfred Bulter.
              </div>
              <div class="col-xs-4">
                  <ul class="pull-right list-inline m-b-0">
                      <li>
                          <a href="#">About</a>
                      </li>
                      <li>
                          <a href="#">Help</a>
                      </li>
                      <li>
                          <a href="#">Contact</a>
                      </li>
                  </ul>
              </div>
          </div>
      </div>
  </footer>
  <!-- End Footer -->

app/views/common/_header.html.erb
          <!-- Navigation Bar-->
          <header id="topnav">
              <div class="topbar-main">
                  <div class="container">

                      <!-- LOGO -->
                      <div class="topbar-left">
                          <a href="<%= root_url %>" class="logo"><span>Alfred<span> Bulter</span></span></a>
                      </div>
                      <!-- End Logo container-->


                      <div class="menu-extras">
                          <ul class="nav navbar-nav navbar-right pull-right">
                              <li>
                                  <!-- Notification -->
                                  <!--
                                  <div class="notification-box">
                                      <ul class="list-inline m-b-0">
                                          <li>
                                              <a href="javascript:void(0);" class="right-bar-toggle">
                                                  <i class="zmdi zmdi-notifications-none"></i>
                                              </a>
                                              <div class="noti-dot">
                                                  <span class="dot"></span>
                                                  <span class="pulse"></span>
                                              </div>
                                          </li>
                                      </ul>
                                  </div>
                                  -->
                                  <!-- End Notification bar -->

                              </li>

                              <!--
                              <li class="dropdown user-box">
                                  <a href="" class="dropdown-toggle waves-effect waves-light profile " data-toggle="dropdown" aria-expanded="true">
                                      <img src="<%= current_shop.avatar.url %>" alt="<%= current_shop.name %>" class="img-circle user-img">
                                      <div class="user-status away">
                                        <i class="zmdi zmdi-dot-circle"></i>
                                      </div>
                                  </a>

                                  <ul class="dropdown-menu">
                                      <li><a href="javascript:void(0)"><i class="ti-user m-r-5"></i> Profile</a></li>
                                      <li><a href="javascript:void(0)"><i class="ti-settings m-r-5"></i> Settings</a></li>
                                      <li><a href="javascript:void(0)"><i class="ti-lock m-r-5"></i> Lock screen</a></li>
                                      <li><a href="javascript:void(0)"><i class="ti-power-off m-r-5"></i> Logout</a></li>
                                  </ul>
                              </li>
                              -->
                          </ul>
                          <div class="menu-item">
                              <!-- Mobile menu toggle-->
                              <a class="navbar-toggle">
                                  <div class="lines">
                                      <span></span>
                                      <span></span>
                                      <span></span>
                                  </div>
                              </a>
                              <!-- End mobile menu toggle-->
                          </div>
                      </div>

                  </div>
              </div>

              <div class="navbar-custom">
                  <div class="container">
                      <div id="navigation">
                          <!-- Navigation Menu-->
                          <ul class="navigation-menu">
                              <li class="dashboard-navigation active">
                                <a href="<%= root_url %>">
                                  <i class="zmdi zmdi-view-dashboard"></i> <span> Dashboard </span> 
                                </a>
                              </li>
                              <li class="products-navigation">
                                <a href="<%= products_url %>">
                                  <i class="zmdi zmdi-collection-item"></i> <span> Products </span> 
                                </a>
                              </li>
                              <li class="products-profile-navigation">
                                <a href="<%= product_profiles_url %>">
                                  <i class="zmdi zmdi-collection-item"></i> <span> Product Importer </span> 
                                </a>
                              </li>
                              <li class="faq-navigation">
                                <a href="<%= faq_index_url %>">
                                  <i class="zmdi zmdi-help-outline"></i> <span> FAQ </span> 
                                </a>
                              </li>
                          </ul>
                          <!-- End navigation menu  -->
                      </div>
                  </div>
              </div>
          </header>
          <!-- End Navigation Bar-->

app/views/common/_notifications.html.erb
              <!-- Right Sidebar -->
              <div class="side-bar right-bar">
                  <a href="javascript:void(0);" class="right-bar-toggle">
                      <i class="zmdi zmdi-close-circle-o"></i>
                  </a>
                  <h4 class="">Notifications</h4>
                  <div class="notification-list nicescroll">
                      <ul class="list-group list-no-border user-list">
                          <li class="list-group-item">
                              <a href="#" class="user-list-item">
                                  <div class="avatar">
                                      <img src="assets/images/users/avatar-2.jpg" alt="">
                                  </div>
                                  <div class="user-desc">
                                      <span class="name">Michael Zenaty</span>
                                      <span class="desc">There are new settings available</span>
                                      <span class="time">2 hours ago</span>
                                  </div>
                              </a>
                          </li>
                          <li class="list-group-item">
                              <a href="#" class="user-list-item">
                                  <div class="icon bg-info">
                                      <i class="zmdi zmdi-account"></i>
                                  </div>
                                  <div class="user-desc">
                                      <span class="name">New Signup</span>
                                      <span class="desc">There are new settings available</span>
                                      <span class="time">5 hours ago</span>
                                  </div>
                              </a>
                          </li>
                          <li class="list-group-item">
                              <a href="#" class="user-list-item">
                                  <div class="icon bg-pink">
                                      <i class="zmdi zmdi-comment"></i>
                                  </div>
                                  <div class="user-desc">
                                      <span class="name">New Message received</span>
                                      <span class="desc">There are new settings available</span>
                                      <span class="time">1 day ago</span>
                                  </div>
                              </a>
                          </li>
                          <li class="list-group-item active">
                              <a href="#" class="user-list-item">
                                  <div class="avatar">
                                      <img src="assets/images/users/avatar-3.jpg" alt="">
                                  </div>
                                  <div class="user-desc">
                                      <span class="name">James Anderson</span>
                                      <span class="desc">There are new settings available</span>
                                      <span class="time">2 days ago</span>
                                  </div>
                              </a>
                          </li>
                          <li class="list-group-item active">
                              <a href="#" class="user-list-item">
                                  <div class="icon bg-warning">
                                      <i class="zmdi zmdi-settings"></i>
                                  </div>
                                  <div class="user-desc">
                                      <span class="name">Settings</span>
                                      <span class="desc">There are new settings available</span>
                                      <span class="time">1 day ago</span>
                                  </div>
                              </a>
                          </li>

                      </ul>
                  </div>
              </div>
              <!-- /Right-bar -->

app/views/common/_page_title.html.erb
  <div class="row">
      <div class="col-sm-12">
          <!--
          <div class="btn-group pull-right m-t-15">
              <button type="button" class="btn btn-custom dropdown-toggle waves-effect waves-light" data-toggle="dropdown" aria-expanded="false">Settings <span class="m-l-5"><i class="fa fa-cog"></i></span></button>
              <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Separated link</a></li>
              </ul>
          </div>
          -->
          <h4 class="page-title"><%= page_title %></h4>
      </div>
  </div>

app/views/common/_products_datatable.html.erb
<div class="row">
    <div class="col-sm-12">
        <div class="card-box table-responsive">
            <h4 class="header-title m-t-0 m-b-30">Products</h4>
            <table id="datatable-responsive" class="table table-bordered dt-responsive nowrap" cellspacing="0" width="100%" data-url="<%= products_url(format: "json") %>" >
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Vendor</th>
                        <th>Tags</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/common/_setup_requests_datatable.html.erb
<div class="row">
    <div class="col-sm-12">
        <div class="card-box table-responsive">
            <h4 class="header-title m-t-0 m-b-30">
                <%= setup.index_link %>
                <div class="pull-right">
                    <%= setup.new_btn %>
                </div>
            </h4>
            <table id="datatable-responsive" class="table table-bordered dt-responsive nowrap" cellspacing="0" width="100%" data-url="<%= setup_requests_url(format: "json") %>" >
                <thead>
                    <tr>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/common/_variants_datatable.html.erb
<div class="row">
    <div class="col-sm-12">
        <div class="card-box table-responsive">
            <h4 class="header-title m-t-0 m-b-30">Variants</h4>
            <table id="datatable-responsive" class="table table-bordered dt-responsive nowrap" cellspacing="0" width="100%" data-url="<%= stocks_url(format: "json") %>" >
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>SKU</th>
                        <th>Quantity</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/common/_zopim.html.erb
<% if Settings.features.zopim %>
<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set._.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");$.src="//v2.zopim.com/?467D52jtci4twJvRQtMpGF56TV4uaOn0";z.t=+new Date;$.type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");

</script>
<!--End of Zopim Live Chat Script-->
<% end %>